---
title: "PH1930 Final Project: Method Comparison"
author: "Group 2: Yu Bin Chen, Rachit Sabharwal, Caroline Schaefer, Pagna Sok"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

##### This report and scripts are being submitted early for review and feedback.  
It contains results for the CD and ADMM algorithms using both R and C++ then compares the results using identical random sample inputs.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(Rcpp)
library(RcppArmadillo)

source("project_functions.R")
sourceCpp("coordinate_descent_algo.cpp")
sourceCpp("admm_cpp.cpp")
```


```{r}
#set parameters for simulation
rho <- 0.9
n <- 200
p <- 4

#create covariance matrix
cov_matrix <- matrix(0, nrow = p, ncol = p)
for (i in 1:p) {
  for (j in 1:p) {
    cov_matrix[i, j] <- rho^abs(i - j)
  }
}

#simulate data
set.seed(100)  # for reproducibility
X <- MASS::mvrnorm(n = n, mu = rep(0, p), Sigma = cov_matrix)

#set b
b <- c(1, rep(0, p - 1))

#lambda value
lambda_value <- 0.01

#ADMM  and CD algorithms and compare their results
cd_r <- cg_cd(X, b, lambda_value)
cd_cpp <- cg_cd_cpp(X, b, lambda_value)
admm_r <- cg_admm(X, b, lambda_value)
admm_cpp <- cg_admm_cpp(X, b, lambda_value, 1e-4, 1000)
```


***
# Coordinate Descent

```{r}
print(cd_r)
print(cd_cpp)
```

***
# ADMM
```{r}
print(admm_r)
print(admm_cpp)
```

