---
title: "PH1930 Final Project"
author: "Group 2: Yu Bin Chen, Rachit Sabharwal, Caroline Schaefer, Pagna Sok"
date: "2023-12-10"
output:
  html_document: default
  pdf_document: default
---

This report contains results of minimizing the equation using the coordinate descent (CD) and alternating direction method of multipliers (ADMM). Functions are run using C++ code and implemented with the R packages Rcpp and RcppArmadillo: 

\begin{align*}
\frac{1}{2}u^TAu-ub^T+\lambda ||u||_1\\
\end{align*}  


```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(Rcpp)
library(RcppArmadillo)

sourceCpp("coordinate_descent_algo.cpp")
sourceCpp("admm_cpp_v3.cpp")
```


```{r}
#set parameters for simulation
rho <- 0.9
n <- 200
p <- 4

#create covariance matrix
cov_matrix <- matrix(0, nrow = p, ncol = p)
for (i in 1:p) {
  for (j in 1:p) {
    cov_matrix[i, j] <- rho^abs(i - j)
  }
}

#simulate data
set.seed(100)  # for reproducibility
X <- MASS::mvrnorm(n = n, mu = rep(0, p), Sigma = cov_matrix)

#set b
b <- c(1, rep(0, p - 1))

#lambda value
lambda <- 0.01

#ADMM  and CD algorithms and compare their results
cd <- cg_cd(X, b, lambda, tol=1e-4, maxit = 1000)
admm <- cg_admm(X, b, lambda, tol=1e-4, maxit = 1000)
```


***
# Coordinate Descent

```{r}
print(cd)
```

***
# ADMM
```{r}
print(admm)
```

